# Generated by Django 3.0.7 on 2020-10-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=200)),
                ('project_timeDate', models.DateTimeField(auto_now_add=True)),
                ('project_descriptions', models.TextField()),
                ('project_youtubeUrl', models.TextField(blank=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
        ),
    ]
